pipeline{
    agent any

    stages{
        stages("Test"){
            steps {
                sh 'mvn test'
            }
            post {
                always{
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}